import Link from "next/link"
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <nav className=" w-full h-full flex flex-row gap-2" >
            <Link href="/">Home</Link>
            <Link href="/articles">articles</Link>
            <Link href="/posts">posts</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
